### ISSUE TITLE
The public site is returning 500 errors (for all new uploads?)

### ISSUE THREAD

**Issue by deliciouslytyped** [cpu/AndroidObservatory#2]
https://androidobservatory.org/ seems to be returning 500 errors for the detailed pages for APKs.
Search does appear to work still.
https://androidobservatory.org/cert/61ED377E85D386A8DFEE6B864BD85B0BFAA5AF81 still works.

**Comment by deliciouslytyped** [comment]
Thanks for making this service.
This is the first time I've tried it.
I was attempting to verify the certificate of an APK for which I did not have access to an original copy.

**Comment by cpu** [comment]
:wave: Hi @deliciouslytyped,

Apologies but I haven't been involved in the Android Observatory in a long time and have no operational access to the running website. This repo is largely an archive of the original source code.

I recommend you contact [Ilja Gerhardt](https://gerhardt.ch/). They have been operating the observatory for the past 6 years or so.
